Controllers/LessonsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolBackoffice.Data;
using SchoolBackoffice.Models;

namespace SchoolBackoffice.Controllers
{
    public class LessonsController : Controller
    {
        private readonly SchoolBackofficeContext _context;

        private readonly string[] Days = new[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };

        private readonly string[] Subjects = new[] { "English", "Mathematics", "Polish", "Physical Education", "Physics", "Chemistry", "Geography", "Biology", "History", "Information Technology", "Music", "Religious Education" };

        public LessonsController(SchoolBackofficeContext context)
        {
            _context = context;
        }

        // GET: Lessons
        public async Task<IActionResult> Index()
        {
            ViewData["Teachers"] = _context.Teachers.Count() != 0;
            var SchoolBackofficeContext = _context.Lessons.Include(l => l.Teacher);
            return View(await SchoolBackofficeContext.ToListAsync());
        }

        // GET: Lessons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons
                .Include(l => l.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // GET: Lessons/Create
        [Authorize]
        public IActionResult Create()
        {
            if (_context != null && _context.Teachers != null && _context.Teachers.Count() != 0)
            {
                ViewData["Teacher"] = new SelectList(_context.Teachers, "Id", null, _context.Teachers.First());
                ViewData["WeekDays"] = Days.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == Days[0] });
                ViewData["Subjects"] = Subjects.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == Subjects[0] });
                return View();
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Type,WeekDay,DateStart,Duration,TeacherId")] Lesson lesson)
        {
            if (ModelState.IsValid)
            {
                lesson.Teacher = await _context.Teachers.FindAsync(lesson.TeacherId);
                _context.Add(lesson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Teacher"] = new SelectList(_context.Teachers, "Id", null, lesson.Teacher);
            ViewData["WeekDays"] = Days.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.WeekDay });
            ViewData["Subjects"] = Subjects.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.Type });
            return View(lesson);
        }

        // GET: Lessons/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons.FindAsync(id);
            if (lesson == null)
            {
                return NotFound();
            }
            ViewData["Teacher"] = new SelectList(_context.Teachers, "Id", null, lesson.TeacherId);
            ViewData["WeekDays"] = Days.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.WeekDay });
            ViewData["Subjects"] = Subjects.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.Type });
            return View(lesson);
        }

        // POST: Lessons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,WeekDay,DateStart,Duration,TeacherId")] Lesson lesson)
        {
            if (id != lesson.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lesson);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LessonExists(lesson.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Teacher"] = new SelectList(_context.Teachers, "Id", "Name", lesson.Teacher);
            ViewData["WeekDays"] = Days.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.WeekDay });
            ViewData["Subjects"] = Subjects.Select(x => new SelectListItem() { Text = x, Value = x, Selected = x == lesson.Type });
            return View(lesson);
        }

        // GET: Lessons/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lessons == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons
                .Include(l => l.Teacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lessons == null)
            {
                return Problem("Entity set 'SchoolBackofficeContext.Lesson'  is null.");
            }
            var lesson = await _context.Lessons.FindAsync(id);
            if (lesson != null)
            {
                _context.Lessons.Remove(lesson);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LessonExists(int id)
        {
          return (_context.Lessons?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School Backoffice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolCalendar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School Backoffice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Lessons" asp-action="Index">Lessons</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - School Backoffice
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>